### ISSUE TITLE
Trading card game

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#84]
A side feature, a simplified version of the Pokémon trading card game.

**Comment by yuhasem** [comment]
I protoyped a card game [here](https://github.com/yuhasem/Ishadijcks.github.io/tree/card-game). It wasn't too hard to get most of the mechanics from the games working so the only one I've left out right now is retreat costs. Since this was just a prototype I didn't put any polish on the UI or descriptions on card attacks/abilities. For right now, you get a small deck based on your starter and if you want more you have to set it through the console by doing
`player.cards.availableCard[<card name>] = <amount>`

Some known issues that I'll be working on:
- Order of logging when the game ends by a pokemon fainting
- AI is terrible
- Order of recoil damage and attack damage

Mostly I wanted to post this so that we can start thinking about what mechanics we want to include/remove from the card game and how this will fit into the game as a whole (what currencies, upgrades, benefits will it have?)
